server.port=8080

client.url=http://localhost:9090/main
spring.datasource.username=main
spring.datasource.password=main

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
stats-server.url=http://localhost:9090