DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE ;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    category BIGINT NOT NULL,
    paid BOOLEAN,
    event_date TIMESTAMP NOT NULL,
    initiator BIGINT NOT NULL,
    description VARCHAR(7000) NOT NULL,
    created_on TIMESTAMP NOT NULL,
    participant_limit INTEGER,
    request_moderation BOOLEAN,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    state VARCHAR(255) NOT NULL,
    published_on TIMESTAMP,
    CONSTRAINT fk_category FOREIGN KEY (category) REFERENCES categories(id),
    CONSTRAINT fk_initiator FOREIGN KEY (initiator) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_request_requester FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT uq_request UNIQUE (requester_id, event_id)
);
