stat-server.url=http://localhost:9090
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/stats
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info