server.port=9090

client.url=http://localhost:8080/stat
spring.datasource.username=stat
spring.datasource.password=stat

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info

stats-server.url=http://localhost:9090